ERROR - 2024-12-30 05:58:50 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter-mysql\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\codeigniter-mysql\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'record', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter-mysql\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter-mysql\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter-mysql\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `re...', Array, false)
#4 C:\xampp\htdocs\codeigniter-mysql\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter-mysql\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter-mysql\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter-mysql\app\Controllers\RecordController.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter-mysql\system\CodeIgniter.php(933): App\Controllers\RecordController->create()
#9 C:\xampp\htdocs\codeigniter-mysql\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RecordController))
#10 C:\xampp\htdocs\codeigniter-mysql\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter-mysql\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter-mysql\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\codeigniter-mysql\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\codeigniter-mysql\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\codeigniter-mysql\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\codeigniter-mysql\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter-mysql\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter-mysql\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `re...', Array, false)
#3 C:\xampp\htdocs\codeigniter-mysql\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\codeigniter-mysql\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\codeigniter-mysql\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\codeigniter-mysql\app\Controllers\RecordController.php(21): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\codeigniter-mysql\system\CodeIgniter.php(933): App\Controllers\RecordController->create()
#8 C:\xampp\htdocs\codeigniter-mysql\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RecordController))
#9 C:\xampp\htdocs\codeigniter-mysql\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter-mysql\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\codeigniter-mysql\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\codeigniter-mysql\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\codeigniter-mysql\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-12-30 05:58:50 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `records` (`name`, `email`) VALUES (:name:, :email:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\RecordController.php(21): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\RecordController->create()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RecordController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter-mysql\\public\\index.php')
CRITICAL - 2024-12-30 06:33:33 --> CodeIgniter\HTTP\Exceptions\HTTPException: 7 : Failed to connect to localhost port 3000 after 2057 ms: Couldn't connect to server
[Method: POST, Route: create-record]
in SYSTEMPATH\HTTP\CURLRequest.php on line 694.
 1 SYSTEMPATH\HTTP\CURLRequest.php(694): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('7', 'Failed to connect to localhost port 3000 after 2057 ms: Couldn\'t connect to server')
 2 SYSTEMPATH\HTTP\CURLRequest.php(383): CodeIgniter\HTTP\CURLRequest->sendRequest([...])
 3 SYSTEMPATH\HTTP\CURLRequest.php(152): CodeIgniter\HTTP\CURLRequest->send('POST', 'http://localhost:3000/sync-mongodb')
 4 SYSTEMPATH\HTTP\CURLRequest.php(227): CodeIgniter\HTTP\CURLRequest->request('POST', 'http://localhost:3000/sync-mongodb', [...])
 5 APPPATH\Controllers\RecordController.php(117): CodeIgniter\HTTP\CURLRequest->post('http://localhost:3000/sync-mongodb', [...])
 6 APPPATH\Controllers\RecordController.php(42): App\Controllers\RecordController->triggerAPI([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\RecordController->create()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RecordController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter-mysql\\public\\index.php')
CRITICAL - 2024-12-30 06:56:51 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: delete-record/2]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\RecordController.php(122): CodeIgniter\Model->update('1', [...])
 4 APPPATH\Controllers\RecordController.php(96): App\Controllers\RecordController->renumberMySQLRecords()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\RecordController->delete('2')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RecordController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter-mysql\\public\\index.php')
CRITICAL - 2024-12-30 07:00:56 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: delete-record/5]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\RecordController.php(127): CodeIgniter\Model->update('4', [...])
 4 APPPATH\Controllers\RecordController.php(96): App\Controllers\RecordController->renumberMySQLRecords()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\RecordController->delete('5')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RecordController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter-mysql\\public\\index.php')
